apiVersion: apps/v1
kind: Deployment
metadata:
  name: kastro-exam-deployment
  namespace: devopsapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kastro-exam
  template:
    metadata:
      labels:
        app: kastro-exam
    spec:
      containers:
        - name: kastro-exam-container
          image: kastrov/kastro-exam-app:v1
          ports:
            - containerPort: 8000
          env:
            - name: DB_HOST
              value: "mysql-service"
            - name: DB_USER
              value: "root"
            - name: DB_PASSWORD
              value: "password"
            - name: DB_NAME
              value: "exam_db"
