apiVersion: v1
kind: Service
metadata:
  name: kastro-exam-service
  namespace: devopsapp
spec:
  type: LoadBalancer
  selector:
    app: kastro-exam
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
